//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisaSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appilcant
    {
        public int AppID { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int CityID { get; set; }
        public int CountryID { get; set; }
        public int VisaID { get; set; }
        public int StatusID { get; set; }
    
        public virtual Cities City { get; set; }
        public virtual Countries Countries_ { get; set; }
        public virtual VisaStatu VisaStatu { get; set; }
        public virtual VisaTypes VisaType { get; set; }
    }
}
